#!/usr/bin/env sh
mkdir -p temp
curl https://mapicons.mapsmarker.com/wp-content/uploads/zip/mapiconscollection-markers.zip -o temp/mapiconscollection-markers.zip
unzip -o temp/mapiconscollection-markers.zip -d temp/
mkdir -p src/assets/category/
cp temp/award.png src/assets/category/all.png
cp temp/award.png src/assets/category/amenity.png
cp temp/award.png src/assets/category/historic.png
cp temp/award.png src/assets/category/leisure.png
cp temp/award.png src/assets/category/man_made.png
cp temp/award.png src/assets/category/shop.png
cp temp/award.png src/assets/category/sport.png
cp temp/award.png src/assets/category/tourism.png
cp temp/restaurant.png src/assets/category/restaurant.png
cp temp/bank_euro.png src/assets/category/bank.png
cp temp/postal.png src/assets/category/postbox.png
cp temp/icecream.png src/assets/category/icecream.png
cp temp/hunting.png src/assets/category/hunting.png
cp temp/cinema.png src/assets/category/cinema.png
cp temp/church-2.png src/assets/category/church.png
cp temp/picnic-2.png src/assets/category/bench.png
cp temp/fillingstation.png src/assets/category/fuel.png
cp temp/busstop.png src/assets/category/shelter.png
cp temp/parkinggarage.png src/assets/category/parking.png
cp temp/barbecue.png src/assets/category/barbecue.png
cp temp/school.png src/assets/category/school.png
cp temp/nursery.png src/assets/category/kindergarten.png
cp temp/daycare.png src/assets/category/childcare.png
cp temp/dentist.png src/assets/category/dentist.png
cp temp/library.png src/assets/category/library.png
cp temp/toilets_inclusive.png src/assets/category/toilets.png
cp temp/gumball_machine.png src/assets/category/vendor.png
cp temp/theater.png src/assets/category/theater.png
cp temp/taxi.png src/assets/category/taxi.png
cp temp/police.png src/assets/category/police.png
cp temp/hospital-building.png src/assets/category/hospital.png
cp temp/nursing_home_icon.png src/assets/category/socialfacility.png
cp temp/fountain-3.png src/assets/category/fountain.png
cp temp/bicycle_parking.png src/assets/category/bicycleparking.png
cp temp/busstop.png src/assets/category/busstation.png
cp temp/firemen.png src/assets/category/firestation.png
cp temp/recycle.png src/assets/category/recycling.png
cp temp/medicine.png src/assets/category/doctor.png
cp temp/medicalstore.png src/assets/category/pharmacy.png
cp temp/telephone.png src/assets/category/telephone.png
cp temp/clock.png src/assets/category/clock.png
cp temp/castle-2.png src/assets/category/castle.png
cp temp/veterinary.png src/assets/category/veterinary.png
cp temp/carwash.png src/assets/category/carwash.png
cp temp/memorial.png src/assets/category/memorial.png
cp temp/megalith.png src/assets/category/megalith.png
cp temp/historicalquarter.png src/assets/category/ruins.png
cp temp/playground.png src/assets/category/playground.png
cp temp/swimming.png src/assets/category/swimming.png
cp temp/riparianhabitat.png src/assets/category/park.png
cp temp/lighthouse-2.png src/assets/category/lighthouse.png
cp temp/watermill-2.png src/assets/category/watermill.png
cp temp/mobilephonetower.png src/assets/category/mast.png
cp temp/metronetwork.png src/assets/category/exchange.png
cp temp/bread.png src/assets/category/bakery.png
cp temp/kiosk.png src/assets/category/kiosk.png
cp temp/supermarket.png src/assets/category/supermarket.png
cp temp/barber.png src/assets/category/hairdresser.png
cp temp/butcher-2.png src/assets/category/butcher.png
cp temp/photography.png src/assets/category/photo.png
cp temp/gifts.png src/assets/category/gift.png
cp temp/glasses.png src/assets/category/optician.png
cp temp/garden.png src/assets/category/florist.png
cp temp/shoes.png src/assets/category/shoes.png
cp temp/phones.png src/assets/category/electronic.png
cp temp/clothers_male.png src/assets/category/clothes.png
cp temp/travel_agency.png src/assets/category/travel.png
cp temp/conveniencestore.png src/assets/category/convenience.png
cp temp/bicycle_shop.png src/assets/category/bicycle.png
cp temp/hoergeraeteakustiker_22px.png src/assets/category/hearingaids.png
cp temp/car.png src/assets/category/car.png
cp temp/liquor.png src/assets/category/beverage.png
cp temp/farmstand.png src/assets/category/farm.png
cp temp/pets.png src/assets/category/pet.png
cp temp/motorcycle.png src/assets/category/motorcycle.png
cp temp/tools.png src/assets/category/doityourself.png
cp temp/perfumery.png src/assets/category/chemist.png
cp temp/grocery.png src/assets/category/healthfood.png
cp temp/climbing.png src/assets/category/climbing.png
cp temp/bowling.png src/assets/category/bowling.png
cp temp/iceskating.png src/assets/category/iceskating.png
cp temp/museum_openair.png src/assets/category/attraction.png
cp temp/campingcar.png src/assets/category/camping.png
cp temp/bed_breakfast1-2.png src/assets/category/hotel.png
cp temp/information.png src/assets/category/information.png
cp temp/museum_art.png src/assets/category/museum.png
cp temp/picnic-2.png src/assets/category/picnic.png
cp temp/themepark.png src/assets/category/themepark.png
cp temp/landmark.png src/assets/category/viewpoint.png
cp temp/zoo.png src/assets/category/zoo.png
